<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="10" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="1298241" started-at="2016-08-10T09:38:27Z" finished-at="2016-08-10T10:00:05Z">
    <groups>
    </groups>
    <test name="Login" duration-ms="4083" started-at="2016-08-10T09:38:27Z" finished-at="2016-08-10T09:38:31Z">
      <class name="com.spicespirittest.testcase.LoginTest">
        <test-method status="PASS" signature="loginTest()[pri:0, instance:com.spicespirittest.testcase.LoginTest@5c7fa833]" name="loginTest" duration-ms="4064" started-at="2016-08-10T17:38:27Z" finished-at="2016-08-10T17:38:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
      </class> <!-- com.spicespirittest.testcase.LoginTest -->
    </test> <!-- Login -->
    <test name="LogisticsCreateTodayData" duration-ms="3990" started-at="2016-08-10T09:38:31Z" finished-at="2016-08-10T09:38:35Z">
      <class name="com.spicespirittest.testcase.LogisticsCreateTodayDataTest">
        <test-method status="FAIL" signature="logisticsCreateTodayDataTest()[pri:0, instance:com.spicespirittest.testcase.LogisticsCreateTodayDataTest@3532ec19]" name="logisticsCreateTodayDataTest" duration-ms="3987" started-at="2016-08-10T17:38:31Z" finished-at="2016-08-10T17:38:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [今天的数据已经生成,不用生成数据] but found [今日数据生成完毕]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [今天的数据已经生成,不用生成数据] but found [今日数据生成完毕]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.spicespirittest.testcase.LogisticsCreateTodayDataTest.logisticsCreateTodayDataTest(LogisticsCreateTodayDataTest.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logisticsCreateTodayDataTest -->
      </class> <!-- com.spicespirittest.testcase.LogisticsCreateTodayDataTest -->
    </test> <!-- LogisticsCreateTodayData -->
    <test name="LogisticsGoodsApplication" duration-ms="61619" started-at="2016-08-10T09:38:35Z" finished-at="2016-08-10T09:39:37Z">
      <class name="com.spicespirittest.testcase.LogisticsGoodsApplicationTest">
        <test-method status="PASS" signature="logisticsGoodsApplicationTest()[pri:0, instance:com.spicespirittest.testcase.LogisticsGoodsApplicationTest@1bce4f0a]" name="logisticsGoodsApplicationTest" duration-ms="61616" started-at="2016-08-10T17:38:35Z" finished-at="2016-08-10T17:39:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logisticsGoodsApplicationTest -->
      </class> <!-- com.spicespirittest.testcase.LogisticsGoodsApplicationTest -->
    </test> <!-- LogisticsGoodsApplication -->
    <test name="Centerstock" duration-ms="125285" started-at="2016-08-10T09:39:37Z" finished-at="2016-08-10T09:41:42Z">
      <class name="com.spicespirittest.testcase.CenterStockTest">
        <test-method status="FAIL" signature="centerStockTest()[pri:0, instance:com.spicespirittest.testcase.CenterStockTest@7cd62f43]" name="centerStockTest" duration-ms="125281" started-at="2016-08-10T17:39:37Z" finished-at="2016-08-10T17:41:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [采购单创建成功!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [采购单创建成功!]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.spicespirittest.testcase.CenterStockTest.centerStockTest(CenterStockTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- centerStockTest -->
      </class> <!-- com.spicespirittest.testcase.CenterStockTest -->
    </test> <!-- Centerstock -->
    <test name="CenterStockUnConfirm" duration-ms="17177" started-at="2016-08-10T09:41:42Z" finished-at="2016-08-10T09:41:59Z">
      <class name="com.spicespirittest.testcase.CenterStockUnConfirmTest">
        <test-method status="PASS" signature="centerStockUnConfirm()[pri:0, instance:com.spicespirittest.testcase.CenterStockUnConfirmTest@42e26948]" name="centerStockUnConfirm" duration-ms="17175" started-at="2016-08-10T17:41:42Z" finished-at="2016-08-10T17:41:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- centerStockUnConfirm -->
      </class> <!-- com.spicespirittest.testcase.CenterStockUnConfirmTest -->
    </test> <!-- CenterStockUnConfirm -->
    <test name="CenterInStock" duration-ms="758903" started-at="2016-08-10T09:41:59Z" finished-at="2016-08-10T09:54:38Z">
      <class name="com.spicespirittest.testcase.CenterInStockTest">
        <test-method status="PASS" signature="centerInStockTest()[pri:0, instance:com.spicespirittest.testcase.CenterInStockTest@77cd7a0]" name="centerInStockTest" duration-ms="758902" started-at="2016-08-10T17:41:59Z" finished-at="2016-08-10T17:54:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- centerInStockTest -->
      </class> <!-- com.spicespirittest.testcase.CenterInStockTest -->
    </test> <!-- CenterInStock -->
    <test name="CenterOuStock" duration-ms="299878" started-at="2016-08-10T09:54:38Z" finished-at="2016-08-10T09:59:38Z">
      <class name="com.spicespirittest.testcase.CenterOuStockTest">
        <test-method status="PASS" signature="ceterOutStock()[pri:0, instance:com.spicespirittest.testcase.CenterOuStockTest@f6c48ac]" name="ceterOutStock" duration-ms="299871" started-at="2016-08-10T17:54:38Z" finished-at="2016-08-10T17:59:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ceterOutStock -->
      </class> <!-- com.spicespirittest.testcase.CenterOuStockTest -->
    </test> <!-- CenterOuStock -->
    <test name="LogisticsGoodsInStock" duration-ms="1" started-at="2016-08-10T09:59:38Z" finished-at="2016-08-10T09:59:38Z">
    </test> <!-- LogisticsGoodsInStock -->
    <test name="Order" duration-ms="12866" started-at="2016-08-10T09:59:38Z" finished-at="2016-08-10T09:59:51Z">
      <class name="com.spicespirittest.testcase.OrderTest">
        <test-method status="PASS" signature="orderTest()[pri:0, instance:com.spicespirittest.testcase.OrderTest@402a079c]" name="orderTest" duration-ms="12864" started-at="2016-08-10T17:59:38Z" finished-at="2016-08-10T17:59:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderTest -->
      </class> <!-- com.spicespirittest.testcase.OrderTest -->
    </test> <!-- Order -->
    <test name="OrderReserve" duration-ms="12485" started-at="2016-08-10T09:59:51Z" finished-at="2016-08-10T10:00:04Z">
      <class name="com.spicespirittest.testcase.OrderReserveTest">
        <test-method status="PASS" signature="orderReserveTest()[pri:0, instance:com.spicespirittest.testcase.OrderReserveTest@5700d6b1]" name="orderReserveTest" duration-ms="12483" started-at="2016-08-10T17:59:51Z" finished-at="2016-08-10T18:00:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- orderReserveTest -->
      </class> <!-- com.spicespirittest.testcase.OrderReserveTest -->
    </test> <!-- OrderReserve -->
    <test name="Logout" duration-ms="1871" started-at="2016-08-10T10:00:04Z" finished-at="2016-08-10T10:00:05Z">
      <class name="com.spicespirittest.testcase.LogoutTest">
        <test-method status="PASS" signature="logoutTest()[pri:0, instance:com.spicespirittest.testcase.LogoutTest@490ab905]" name="logoutTest" duration-ms="1869" started-at="2016-08-10T18:00:04Z" finished-at="2016-08-10T18:00:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutTest -->
      </class> <!-- com.spicespirittest.testcase.LogoutTest -->
    </test> <!-- Logout -->
  </suite> <!-- Suite -->
</testng-results>
